### ISSUE TITLE
ISSUE - LFPG Format Change

### ISSUE THREAD

**Issue by chrissKLO** [VATFrance/FR-Sector-File#29]
# Summary of issue/change

LFPG - SMR needs to be changed to the more better [REGION] format.

# Reference (amendment doc/official source/forum) incl. page number(s)

- NIL

# Affected areas of the sector file (if known)

LFPG/SMR/Regions.txt
LFPG/SMR/Geo.txt
LFPG/SMR/Labels.txt

**Comment by fx182ch** [comment]
Hi @chrissKLO ,

I'm the one who made the LFPG layout for when pierr3 created the vSMR plugin. What do you exactly need ? A complete redesign of the ground layout ? Which specific points do you want to improve compared to the current one ? And what do you mean by re-integration ?

**Comment by chrissKLO** [comment]
Hello @fx182ch I suppose you are FXO? Apologies I miss phrased what I wanted to add. At the moment the code for LFPG is set up like this: 

```; - Grass
LFPG_AVISO 3100928 N048.59.53.415 E002.36.06.297
N048.59.55.851 E002.36.35.621
N048.59.59.625 E002.36.36.947
N049.00.02.789 E002.36.36.189
N049.00.04.467 E002.36.34.473
```

The new SMRs we are creating are now in this format:

```;Background
REGIONNAME Le Bourget
smrBackgroundGreen N048.53.41.594 E002.31.36.170
N048.59.47.477 E002.31.18.748
N048.59.29.384 E002.19.56.618
N048.53.31.253 E002.20.01.673
```
My plan was to "redesign" the code into the new format for easier editing later on. "Reintegration" into the new layout we are using for the sectorfile if you can check by the repos layout. We don't need a redesign. The color codes can be found on the master branch under `colors.txt`.

Also if you do not want us to use your layout let us know and we would be than happy to remove it.

**Comment by fx182ch** [comment]
Indeed i am the one in the comment :-)

No feel free to keep using the layout with the same licence. I'll digg in my backups to see if I'm able to found the kml source file for LFPG to add it to this repo for easier update later on.

Regarding the color code, the one used for AVISO LFPG / LFPO (avisoGrass, avisoBuilding , avisoApron , etc..) are (more or less) the one realy used at CDG (based on pictures available on the forum). Do you want me to open a specific issue to discuss this point ?

I would be interessted to work on that issue. I'm not very familiar with the new format but I'll try to prepare a pull request for this issue.

**Comment by chrissKLO** [comment]
Feel free to open up a pull request and include the KML. The color codes are I think still the same in the `colors.txt`. 

Regarding the better format for the REGIONS its as follows:
```
Old format looks like:
; - Grass
LFPG_AVISO 3100928 N048.59.53.415 E002.36.06.297
N048.59.55.851 E002.36.35.621

Comment
REGION Name - Color Code - Coordinates

The new one is like:
;Background
REGIONNAME Le Bourget
smrBackgroundGreen N048.53.41.594 E002.31.36.170

Comment
Region Name
Color Code - Coordinates
```

**Comment by fx182ch** [comment]
Yes but that means that if we want to keep the same AVISO color for LFPG and LFPO we will use aviso color instead of SMR color. E.g: avisoGrass instead of smrBackgroundGreen


An example of new format for CDG would be : 

`;Background
REGIONNAME Charles De Gaulle
avisoGrass N048.59.53.415 E002.36.06.297
N048.59.55.851 E002.36.35.621
N048.59.59.625 E002.36.36.947
N049.00.02.789 E002.36.36.189
N049.00.04.467 E002.36.34.473
`

**Comment by chrissKLO** [comment]
Yes of course replace the color code with the appropriate one :)
